-- 1. Crie uma conta no Supabase (supabase.com)
-- 2. Crie um novo projeto "Ferragens Souza"
-- 3. Vá em "SQL Editor" na barra lateral e cole o código abaixo
-- 4. Clique em "Run"

-- Criação da Tabela de Categorias
CREATE TABLE categories (
  id text PRIMARY KEY,
  name text NOT NULL,
  icon text,
  image text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Criação da Tabela de Produtos
CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price numeric NOT NULL,
  category text REFERENCES categories(id),
  brand text,
  description text,
  specs jsonb, -- Armazena as especificações como JSON
  image text,
  available boolean DEFAULT true,
  featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Ativar RLS (Row Level Security) para segurança
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Política: Qualquer pessoa pode LER (Select) os produtos e categorias
CREATE POLICY "Public categories are viewable by everyone" ON categories FOR SELECT USING (true);
CREATE POLICY "Public products are viewable by everyone" ON products FOR SELECT USING (true);

-- Inserção de Dados Iniciais (Mock Data Sem Imagens)

INSERT INTO categories (id, name, icon, image) VALUES
('eletrica', 'Elétrica', 'Zap', ''),
('iluminacao', 'Iluminação', 'Lightbulb', ''),
('ferramentas', 'Ferramentas', 'Hammer', ''),
('hidraulica', 'Hidráulica', 'Droplets', ''),
('pintura', 'Pintura', 'PaintRoller', ''),
('construcao', 'Construção', 'BrickWall', ''),
('jardinagem', 'Jardinagem', 'Sprout', ''),
('seguranca', 'Segurança', 'Shield', ''),
('fixacao', 'Fixação', 'Wrench', ''),
('utilidades', 'Utilidades', 'Home', '');

INSERT INTO products (name, price, category, brand, description, specs, image, available, featured) VALUES
('Cabo Flexível 2.5mm 750V Rolo 100m', 229.90, 'eletrica', 'Sil', 'Fio de cobre flexível antichama, ideal para tomadas residenciais (10A/20A).', '{"Bitola": "2.5mm", "Comprimento": "100 metros", "Material": "Cobre"}'::jsonb, '', true, true),
('Disjuntor Unipolar DIN 20A Curva C', 22.50, 'eletrica', 'Siemens', 'Disjuntor termomagnético para proteção de circuitos.', '{"Amperagem": "20A", "Pólos": "1", "Curva": "C"}'::jsonb, '', true, false),
('Kit 5 Lâmpadas LED Bulbo 9W Bivolt', 39.90, 'iluminacao', 'Avant', 'Kit econômico. Luz branca fria (6500K).', '{"Potência": "9W", "Fluxo Luminoso": "810lm", "Soquete": "E27"}'::jsonb, '', true, true),
('Torneira Jardim Esfera Metal 1/2"', 35.90, 'hidraulica', 'Deca', 'Alta durabilidade e resistência. Acabamento cromado.', '{"Material": "Metal", "Rosca": "1/2", "Garantia": "10 anos"}'::jsonb, '', true, false),
('Martelo Unha 27mm Cabo Madeira', 45.90, 'ferramentas', 'Tramontina', 'Cabeça forjada e temperada em aço especial.', '{"Tamanho": "27mm", "Cabeça": "Aço Carbono", "Cabo": "Madeira"}'::jsonb, '', true, false),
('Tinta Acrílica Fosca Standard 18L', 359.90, 'pintura', 'Suvinil', 'Tinta de altíssimo rendimento e cobertura.', '{"Volume": "18 Litros", "Cor": "Branco Neve", "Rendimento": "Até 380m²"}'::jsonb, '', true, true);
